In [2]:
import numpy as np

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [98]:
vector = np.random.uniform(low=0, high=1, size=(10))

In [8]:
matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])

In [99]:
print('Вектор "vector":', vector, 'Розмір вектора:', vector.shape)
print('Матриця "matrix":\n', matrix, 'Розмір матриці:', matrix.shape)

Вектор "vector": [0.32306627 0.03529739 0.2988119  0.76165261 0.16147865 0.21967532
 0.61495692 0.73684253 0.10817378 0.26310789] Розмір вектора: (10,)
Матриця "matrix":
 [[22 28 34]
 [40 46 52]
 [58 64 70]] Розмір матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [100]:
v_10 = np.full(10, 10)
vector = vector + v_10
vector = np.round(vector, 2)
vector

array([10.32, 10.04, 10.3 , 10.76, 10.16, 10.22, 10.61, 10.74, 10.11,
       10.26])

In [54]:
matrix = 2 * matrix
matrix

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [101]:
vector_squared = np.multiply(vector, vector)
vector_squared

array([106.5024, 100.8016, 106.09  , 115.7776, 103.2256, 104.4484,
       112.5721, 115.3476, 102.2121, 105.2676])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [24]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [25]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

Множення матриці на вектор дає вектор, розмірність буде (2,1)

In [56]:
res_matr_c = np.dot(result_matrix, C)
res_matr_c

array([[0.5202],
       [0.2846]])

Результатом множення матриць (2,2) на (2,2) буде матриця (2,2). Елементами будуть суми множень відповідних елементів рядка матриці1 на відповідні елементи стопця матриці2.


In [57]:
res_matr_d = np.dot(result_matrix, D)
res_matr_d

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [82]:
result_matrix_t = result_matrix.T
result_matrix_t

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [102]:
vector_t = vector.T
vector, vector.shape, vector_t, vector_t.shape

(array([10.32, 10.04, 10.3 , 10.76, 10.16, 10.22, 10.61, 10.74, 10.11,
        10.26]),
 (10,),
 array([10.32, 10.04, 10.3 , 10.76, 10.16, 10.22, 10.61, 10.74, 10.11,
        10.26]),
 (10,))

Змін немає, вектор-рядок як був так і залишився.

In [107]:
column_vector = np.expand_dims(vector, axis=1)
column_vector, column_vector.shape, vector, vector.shape

(array([[10.32],
        [10.04],
        [10.3 ],
        [10.76],
        [10.16],
        [10.22],
        [10.61],
        [10.74],
        [10.11],
        [10.26]]),
 (10, 1),
 array([10.32, 10.04, 10.3 , 10.76, 10.16, 10.22, 10.61, 10.74, 10.11,
        10.26]),
 (10,))

In [104]:
column_vector_t = column_vector.T
column_vector_t, column_vector.shape

(array([[10.32, 10.04, 10.3 , 10.76, 10.16, 10.22, 10.61, 10.74, 10.11,
         10.26]]),
 (10, 1))

column_vector_t став розширеної розмірності як матриця (10, 1), а не (10,)