In [2]:
import numpy as np
import math

В цьому домашньому завданні ми реалізуємо логістичну регресію на `numpy`.
Ці завдання допоможуть вам ґрунтовно засвоїти основні концепції логістичної регресії та реалізувати їх на практиці 🔥

#### Завдання 1: Реалізація функції сигмоїди
1. З використанням `numpy` напишіть функцію `sigmoid(z)` для обчислення значення сигмоїди згідно з формулою:
   $$
   \sigma(z) = \frac{1}{1 + e^{-z}}
   $$
2. Використовуючи цю функцію, обчисліть значення сигмоїди для наступних даних: $ z = [-2, -1, 0, 1, 2] $. Виведіть результат обчислень.


In [3]:
def sigmoid(x):
  #x = x.dot(x.T)
  s = 1 / (1 + np.exp(-x))
  return s

In [4]:
z_list = np.arange(-2, 3, 1)
z = np.array(z_list)
print(z), z.shape

[-2 -1  0  1  2]


(None, (5,))

In [5]:
z.T

array([-2, -1,  0,  1,  2])

In [6]:
np.dot(z, z.T)

10

In [7]:
sigmoid(z)

array([0.11920292, 0.26894142, 0.5       , 0.73105858, 0.88079708])



#### Завдання 2: Реалізація функції гіпотези для логістичної регресії
1. Напишіть функцію `hypothesis(theta, X)`, яка обчислює гіпотезу для логістичної регресії, використовуючи функцію сигмоїди. Формула гіпотези:
   $$
   h_\theta(x) = \sigma(\theta^T x) = \frac{1}{1 + e^{-\theta^T x}}
   $$
2. Використайте функцію `hypothesis` для обчислення значень гіпотези для наступних даних:
   
   $\theta = [0.5, -0.5]$
   
   $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  Виведіть результат обчислень.


In [8]:
def hypothesis(theta, X):
  x = np.dot(X, theta)
  y = sigmoid(x)
  return y

In [9]:
theta = np.array([0.5, -0.5])
X = np.array([[1, 2],
              [1, -1],
              [1, 0],
              [1, 1]])

In [10]:
g = np.dot(X, theta)
g

array([-0.5,  1. ,  0.5,  0. ])

In [11]:
print(theta), theta.shape, print(X)

[ 0.5 -0.5]
[[ 1  2]
 [ 1 -1]
 [ 1  0]
 [ 1  1]]


(None, (2,), None)

In [12]:
hypothesis(theta, X)

array([0.37754067, 0.73105858, 0.62245933, 0.5       ])

#### Завдання 3: Реалізація функції для підрахунку градієнтів фукнції втрат
1. Напишіть функцію `compute_gradient(theta, X, y)`, яка обчислює градієнти функції втрат для логістичної регресії. Формула для обчислення градієнта:
   $$
   \frac{\partial L(\theta)}{\partial \theta_j} = \frac{1}{m} \sum_{i=1}^{m} \left[ (h_\theta(x^{(i)}) - y^{(i)}) x_j^{(i)} \right]
   $$
2. Використайте функцію `compute_gradient` для обчислення градієнтів для наступних даних:

  $\theta = [0.5, -0.5]$

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Виведіть результат обчислень.

In [13]:
y = np.array([1, 0, 1, 0])

In [14]:
def compute_gradient(theta, X, y):
  m = len(y)
  grad =  np.dot((hypothesis(theta, X) - y), X) / m
  return grad

In [15]:
compute_gradient(theta, X, y)

array([ 0.05776464, -0.36899431])


#### Завдання 4: Реалізація повного батч градієнтного спуску

**Задача:**
1. Напишіть функцію `full_batch_gradient_descent(X, y, lr=0.1, epochs=100)`, яка реалізує алгоритм Full градієнтного спуску для логістичної регресії. Використовуйте такі формули:
   - Гіпотеза: $ h_\theta(x) = \sigma(\theta^T x) $
   - Оновлення параметрів: $ \theta_j := \theta_j - \alpha \frac{\partial L(\theta)}{\partial \theta_j} $
2. Використайте функцію `full_batch_gradient_descent` для обчислення параметрів моделі на наступних даних:

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Увага! Матриця $X$ вже має стовпець одиниць і передбачається, що це. - стовпець для intercept - параметра зсуву.

  Виведіть результат обчислень.


In [16]:
def full_batch_gradient_descent(X, y, lr=0.1, epochs=100):
  gradients = compute_gradient(theta, X, y)
  alpha = lr
  new_theta = theta - alpha * gradients

  return new_theta

In [17]:
full_batch_gradient_descent(X, y, lr=0.1, epochs=100)

array([ 0.49422354, -0.46310057])

In [18]:
new_theta = full_batch_gradient_descent(X, y, lr=0.1, epochs=100)

#### Завдання 5. Обчислення точності моделі

1. Напишіть функцію `predict_proba(theta, X)`, яка використовує знайдені параметри $\theta$ для обчислення ймовірностей належності поточного прикладу з даних до класу $y=1$ на основі значень $\sigma(\theta^T x)$.

2. Напишіть функцію `predict(theta, X, threshold=0.5)`, яка обчислює клас з передбаченої імовірності належності екземпляра до класу 1 з порогом 0.5. Тобто якщо ймовірність менше 0.5, то передбачаємо клас 0, інакше клас 1.

3. Напишіть функцію `accuracy(y_true, y_pred)`, яка обчислює точність моделі, визначивши частку правильно передбачених класів.

  Формула метрики Accuracy:
  $$
  \text{Accuracy} = \frac{\sum_{i=1}^{m} I(\hat{{y}^{(i)}} = y^{(i)})}{m}
  $$

  де $\hat{{y}^{(i)}}$ - передбачене значення класу, $I$ - індикаторна функція (яка дорівнює 1, якщо умова виконується, і 0 - якщо ні), $m$ - кількість прикладів.

4. Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.

5.1

In [19]:
def predict_proba(theta, X):
  predict_proba = hypothesis(theta, X)
  return predict_proba

In [20]:
predict_proba(new_theta, X)

array([0.3936542 , 0.72258573, 0.62110088, 0.50778011])

5.2

In [21]:
def predict(theta, X, treshhold=0.5):
  return predict_proba(theta, X) >= treshhold

In [22]:
predict(new_theta, X, treshhold=0.5)

array([False,  True,  True,  True])

5.3

In [23]:
y_pred_class = predict(new_theta, X)
y_pred_class

array([False,  True,  True,  True])

In [24]:
def true(y, treshhold=0.5):
  y_class = []
  for i in y:
    if i >= treshhold:
      y_class.append(True)
    else:
      y_class.append(False)
  return y_class

In [25]:
y_true_class = true(y)
y_true_class

[True, False, True, False]

In [26]:
def accuracy(y_true, y_pred):

  m = len(y_true)

  sum = np.sum(y_true == y_pred)

  accuracy = sum / m
  return accuracy

In [27]:
accuracy(y_true_class, y_pred_class)

0.25

5.4

In [28]:
print('Передбачені моделлю ймовірності:', predict_proba(new_theta, X))
print('Класи екземплярів:', y_pred_class)
print('Точність моделі:', accuracy(y_true_class, y_pred_class))

Передбачені моделлю ймовірності: [0.3936542  0.72258573 0.62110088 0.50778011]
Класи екземплярів: [False  True  True  True]
Точність моделі: 0.25
